### ISSUE TITLE
hp bios CFG lock?

### ISSUE THREAD

**Issue by freebughao** [lehuutrung1412/Hackintosh-HP-Laptop#2]
Hello, the USB flash drive has been made according to your instructions, but I am stuck on the CFG lock. Have you encountered this problem? How should I close it correctly?

**Comment by lehuutrung1412** [comment]
You can fix that error by following [this](https://dortania.github.io/OpenCore-Post-Install/misc/msr-lock.html#what-is-cfg-lock).

**Comment by freebughao** [comment]
> You can fix that error by following [this](https://dortania.github.io/OpenCore-Post-Install/misc/msr-lock.html#what-is-cfg-lock).

I have tried this method and the result is invalid. Is your bios from the insyde manufacturer?

**Comment by lehuutrung1412** [comment]
Please read carefully the guide that I mentioned in the previous issue. Make sure you disabled AppleCpuPmCfgLock and enabled AppleXcpmCfgLock in Kernel -> Quirks in the config file. I hope this will help :) 

> I have tried this method and the result is invalid. Is your bios from the insyde manufacturer?

**Comment by freebughao** [comment]
> Please read carefully the guide that I mentioned in the previous issue. Make sure you disabled AppleCpuPmCfgLock and enabled AppleXcpmCfgLock in Kernel -> Quirks in the config file. I hope this will help :)
> 
> > I have tried this method and the result is invalid. Is your bios from the insyde manufacturer?

I have tried it. Maybe our laptop model is slightly different, or my laptop is sold in China in some different places. Finally, I switched to clover and installed it successfully. The only problem is the problem of the discrete graphics card driver. I am looking for the driver. R5 M330 graphics card method.

**Comment by lehuutrung1412** [comment]
If you installed it successfully using Clover, I think you can also install it using Opencore. A year ago, I switched from Clover to Opencore. Just try and fix any problems. It's easier than Clover. I read many pages that said Apple did not support our VGA, so there is no kext. You can disable discrete graphics to save power energy.

**Comment by freebughao** [comment]
Oh, I successfully driven the integrated graphics card and output to the monitor through hdmi. Now it is perfectly used for my work. I almost use the notebook as a desktop computer. The resolution of the notebook makes my eyes blind. , Haha
Thank you github for letting me know that this notebook can also eat black apples.
